'use strict';
const assert = require('assert');
const {AllCard,MODES,createWAGONPayment} = require('../../packages/allcard-sdk');
const crypto = require('crypto');
let p=0,f=0;
const t=(n,fn)=>{try{fn();console.log('  ✓',n);p++;}catch(e){console.log('  ✗',n,':',e.message);f++;}};
console.log('\n── allcard-sdk ──');
const card = new AllCard();
t('AllCard: creates with random key', ()=>assert(card.masterKey&&card.masterKey.length===64));
t('shift: returns PAN in right format', ()=>{const s=card.shift();assert(/^\d{4} \d{4} \d{4} \d{4}$/.test(s.pan));});
t('shift: nonce advances each call', ()=>{const n1=card.shift().nonce,n2=card.shift().nonce;assert(n2===n1+1);});
t('shift: 10 calls produce unique PANs', ()=>{const pans=new Set(Array.from({length:10},()=>card.shift().pan));assert(pans.size===10);});
t('shift: mode changes prefix', ()=>{const card2=new AllCard();const id=card2.shift('identity').pan;const db=card2.shift('debit').pan;assert(id.slice(0,4)!==db.slice(0,4));});
t('prove+verify roundtrip', ()=>{const p=card.prove({age_gte:21});assert(card.verify(p.proof,p.commitment));});
t('commit deterministic', ()=>{const k=card.masterKey;const c1=card.commit({x:1});const c2=new AllCard(k).commit({x:1});assert(c1===c2);});
t('encryptVault roundtrip', ()=>{const d={ssn:'123-45-6789'};assert.deepStrictEqual(card.decryptVault(card.encryptVault(d)),d);});
t('fromBiometrics creates AllCard', ()=>{const c=AllCard.fromBiometrics({k:90,v:80});assert(c instanceof AllCard);});
t('paymentRecord: no raw PII', ()=>{const r=card.paymentRecord(100);assert(!JSON.stringify(r).includes(card.masterKey));});
t('paymentRecord: has commitment', ()=>{const r=card.paymentRecord(100);assert(r.commitment&&r.commitment.startsWith('0x'));});
t('createWAGONPayment: R3NET chainId', ()=>{const tx=createWAGONPayment('0xabc','0xdef',100);assert.strictEqual(tx.chainId,720701);});
t('8 MODES exist', ()=>assert(Object.keys(MODES).length===8));
console.log(`\n  ${p}/${p+f} passed`); process.exit(f?1:0);
