
'use strict';
const assert = require('assert');
const zk = require('../../packages/zk-identity');
let p=0,f=0;
const t=(n,fn)=>{try{fn();console.log('  ✓ '+n);p++;}catch(e){console.log('  ✗ '+n+': '+e.message);f++;}};
console.log('\n=== zk-identity ===\n');
t('genKey 64hex',()=>{const k=zk.genKey();assert.strictEqual(k.length,64);assert.match(k,/^[0-9a-f]{64}$/);});
t('genKey random',()=>{assert.strictEqual(new Set(Array.from({length:10},zk.genKey)).size,10);});
t('derivePAN format',()=>{assert.match(zk.derivePAN(zk.genKey(),0).pan,/^\d{4} \d{4} \d{4} \d{4}$/);});
t('derivePAN deterministic',()=>{const k=zk.genKey();assert.strictEqual(zk.derivePAN(k,7).pan,zk.derivePAN(k,7).pan);});
t('derivePAN 20 unique',()=>{const k=zk.genKey();assert.strictEqual(new Set(Array.from({length:20},(_,i)=>zk.derivePAN(k,i).pan)).size,20);});
t('commit 0x+64hex',()=>{assert.match(zk.commit({a:1},zk.genKey()),/^0x[0-9a-f]{64}$/);});
t('commit deterministic',()=>{const k=zk.genKey();assert.strictEqual(zk.commit({a:1},k),zk.commit({a:1},k));});
t('commit unique data',()=>{const k=zk.genKey();assert.notStrictEqual(zk.commit({a:1},k),zk.commit({a:2},k));});
t('prove has fields',()=>{const p=zk.prove({x:1},zk.genKey());assert.ok(p.proof&&p.commitment&&p.timestamp);});
t('prove commitment==commit',()=>{const k=zk.genKey();const d={x:1};assert.strictEqual(zk.prove(d,k).commitment,zk.commit(d,k));});
t('verify true',()=>{const k=zk.genKey();const p=zk.prove({x:1},k);assert.strictEqual(zk.verify(p.proof,p.commitment),true);});
t('verify false invalid',()=>{assert.strictEqual(zk.verify('bad','0x'+'0'.repeat(64)),false);});
t('encrypt has iv+data+tag',()=>{const e=zk.encrypt({s:'SSN'},zk.genKey());assert.ok(e.iv&&e.data&&e.tag);});
t('decrypt roundtrip',()=>{const k=zk.genKey();const d={ssn:'123'};assert.deepStrictEqual(zk.decrypt(zk.encrypt(d,k),k),d);});
t('decrypt wrong key throws',()=>{assert.throws(()=>zk.decrypt(zk.encrypt({x:1},zk.genKey()),zk.genKey()));});
t('encrypt unique IVs',()=>{const k=zk.genKey();assert.notStrictEqual(zk.encrypt({x:1},k).iv,zk.encrypt({x:1},k).iv);});
t('bioDerive deterministic same salt',()=>{const s='aa'+'00'.repeat(31);assert.strictEqual(zk.bioDerive({k:90},s).masterKey,zk.bioDerive({k:90},s).masterKey);});
t('bioDerive random when no salt',()=>{assert.notStrictEqual(zk.bioDerive({k:90}).masterKey,zk.bioDerive({k:90}).masterKey);});
console.log('\n'+p+'/'+(p+f)+' passed'+(f?' FAILED':'  ✓')+'\n');process.exit(f?1:0);
