'use strict';
const assert = require('assert');
const {genKey,derivePAN,commit,prove,verify,bioDerive,encrypt,decrypt} = require('../../packages/zk-identity');
let p=0,f=0;
const t=(n,fn)=>{try{fn();console.log('  ✓',n);p++;}catch(e){console.log('  ✗',n,':',e.message);f++;}};
console.log('\n── zk-identity ──');
t('genKey: 64hex unique', ()=>{const k1=genKey(),k2=genKey();assert(k1!==k2&&k1.length===64);});
t('derivePAN: format', ()=>{assert(/^\d{4} \d{4} \d{4} \d{4}$/.test(derivePAN(genKey(),0).pan));});
t('derivePAN: deterministic', ()=>{const k=genKey();assert(derivePAN(k,5).pan===derivePAN(k,5).pan);});
t('derivePAN: unique 20 nonces', ()=>{const k=genKey();assert(new Set(Array.from({length:20},(_,i)=>derivePAN(k,i).pan)).size===20);});
t('commit: 0x+64hex', ()=>{assert(/^0x[0-9a-f]{64}$/.test(commit({a:1},genKey())));});
t('commit: deterministic', ()=>{const k=genKey();assert(commit({a:1},k)===commit({a:1},k));});
t('prove: commitment matches commit', ()=>{const k=genKey(),d={x:1};assert(prove(d,k).commitment===commit(d,k));});
t('verify: true for valid proof', ()=>{const k=genKey(),p=prove({x:1},k);assert(verify(p.proof,p.commitment)===true);});
t('verify: false for bad proof', ()=>{assert(verify('bad','0x'+'0'.repeat(64))===false);});
t('encrypt/decrypt roundtrip', ()=>{const k=genKey(),d={ssn:'123'};assert.deepStrictEqual(decrypt(encrypt(d,k),k),d);});
t('decrypt fails wrong key', ()=>{assert.throws(()=>decrypt(encrypt({x:1},genKey()),genKey()));});
t('bioDerive deterministic', ()=>{const s='aa'+'00'.repeat(31);assert(bioDerive({k:90},s).masterKey===bioDerive({k:90},s).masterKey);});
console.log(`\n  ${p}/${p+f} passed`); process.exit(f?1:0);
